# Generated by Django 5.1.2 on 2025-04-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='encrypted_api_key',
            new_name='api_key',
        ),
    ]
